spring:
  application:
    name: light-workflow
  datasource:
    url: jdbc:h2:mem:lightworkflow;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.kkooman.lightworkflow
  configuration:
    map-underscore-to-camel-case: true

watchlist:
  search:
    field-weights:
      korean-name: 30
      english-name: 25
      date-of-birth: 15
      country: 8
      residence: 8
      aka: 8
      gender: 3
      listing-reason: 3

server:
  port: 8080
